config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :huddles
  
  resources :participants, only: [:create]

  resources :comments, only: [:create]

  root 'welcome#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :huddle

	validates :name, :message, presence: true
end

app/models/huddle.rb
class Huddle < ActiveRecord::Base
	has_many :participants
	has_many :comments

	validates :subject, :assignment, :creator, :email, :where, :date,
	 :start_time, :end_time, presence: true
end

app/models/participant.rb
class Participant < ActiveRecord::Base
	belongs_to :huddle

	validates :email, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user!
	def create
		@comment = Comment.new(comment_params)
		@comment.name = current_user.name

		if @comment.save
			redirect_to huddle_path(@comment.huddle_id)
		else
			render huddle_path(@commment.huddle_id)
		end
	end
	private
	def comment_params
		params.require(:comment).permit(:name, :message, :huddle_id)
	end
end

app/controllers/huddles_controller.rb
class HuddlesController < ApplicationController
	before_action :authenticate_user!
	def new
		@huddle = Huddle.new
	end

	def index
		@query = params[:query]

		if @query
			@huddles = Huddle.advanced_search(@query)
		else
			@huddles = Huddle.all
		end
	end

	def show
		@huddle = Huddle.find(params[:id])
		@participants = @huddle.participants
		@participant = Participant.new
		@comments = @huddle.comments
		@comment = Comment.new
	end

	def create
		@huddle = Huddle.new(huddle_params)
		@huddle.creator = current_user.name
		@huddle.email = current_user.email

		if @huddle.save
			redirect_to huddles_path
		else
			render :new
		end
	end

	def edit
		@huddle = Huddle.find(params[:id])
	end

	def update
		@huddle = Huddle.find(params[:id])

		if @huddle.update(huddle_params)
			redirect_to huddles_path
		else
			render :edit
		end
	end

	def destroy
		@huddle = Huddle.find(params[:id])

		@huddle.destroy

		redirect_to huddle_path
	end

  private
  	def huddle_params
  		params.require(:huddle).permit(:subject, :assignment, :creator, :email, :where, :start_time,
  			:end_time, :date, :message, :part_max)
  	end
end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
	before_action :authenticate_user!
	def create
		@participant = Participant.new(participant_params)
		@participant.name = current_user.name
		@participant.email = current_user.email
		if @participant.save
			redirect_to huddle_path(@participant.huddle_id)
		else
			render huddle_path(@participant.huddle_id)
		end
	end
	private
	def participant_params
		params.require(:participant).permit(:name, :last_name, :email, :huddle_id)
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_form.html.erb
<% if @comment.errors.present? %>
	<% @comment.errors.full_messages.each do |msg| %>
		<p><%= msg %></p>
	<% end %>
<% end%>

<%= form_for @comment do |f| %>
	<p>
		<%= f.label :message %><br>
		<%= f.text_area :message %>
	</p>
	<%= f.hidden_field :huddle_id, value: @huddle.id %>
	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/huddles/_form.html.erb
<% if @huddle.errors.present? %>
	<% @huddle.errors.full_messages.each do |msg| %>
		<p><%= msg %></p>
	<% end %>
<% end%>

<%= form_for @huddle do |f| %>
<p>
	<%= f.label :class %><br>
	<%= f.text_field :subject %>
</p>
<p>
	<%= f.label :assignment %><br>
	<%= f.text_field :assignment %>
</p>
<p>
	<%= f.label :place %><br>
	<%= f.text_field :where %>
</p>
<p>
	<%= f.label :date %><br>
	<%= f.date_select :date %>
</p>
<p>
	<%= f.label :start_time %><br>
	<%= f.time_select :start_time, ampm: true %>
</p>
<p>
	<%= f.label :end_time %><br>
	<%= f.time_select :end_time, ampm: true %>
</p>
<p>
	<%= f.label :maximum_number_of_participants %><br>
	<%= f.text_field :part_max %>
</p>
<p>
	<%= f.label :message %><br>
	<%= f.text_area :message %>
</p>
<p>
	<%= f.submit %>
</p>
<% end %>

app/views/huddles/index.html.erb
<!-- <h1>Welcome to treeHuddle!</h1>

<% @huddles.each do |huddle| %>
	<h2>Class: <%= huddle.subject %></h2>
	<h3>Assignment: <%= huddle.assignment%> </h3>
	<p>Creator: <%= huddle.creator%> </p>
	<p>Creator's Email: <%= huddle.email%> </p>
	<p>Place: <%= huddle.where%> </p>
	<p>Date:  <%= huddle.date%> </p>
	<p>Start time: <%= huddle.start_time %> </p>
	<p>End time: <%= huddle.end_time %> </p>
	<p>Maximum Number of Participants: <%= huddle.part_max%></p>
	<p>Message: <%= huddle.message%></p>
	
	<%= link_to 'Join this Huddle', huddle_path(huddle) %>
<% end %> -->

    <!-- Page Content -->
    <div class="container">

        <!-- Page Heading -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Welcome to treeHuddle! <br>
                    <small>Your one-stop study group finder.</small>
                </h1>
            </div>
        </div>
        <!-- /.row -->
        <div class="container">
        <div class="row">
            <div class="col-md-10">
                <%= form_tag(huddles_path, method: "get", html: { class: 'form-inline' }) do %>
                <%= label_tag(:query, "Search All Proposals:") %>
                <%= text_field_tag :query, params[@query], placeholder: "Subject, assignment, creator, etc.", input_html: { maxlength: 30 } %>
                <%= submit_tag "Search", class: "btn btn-default" %>
                <% end %>
                <br>
            </div>
        </div>

        <!-- Project One -->
        <% @huddles.each do |huddle| %>
            <% if huddle.part_max > huddle.participants.size %>
                <div class="row">
                    <div class="col-md-4 portfolio-item">
                        <h3><%= huddle.subject %></h3>
                        <h4><%= huddle.assignment%> </h4>
                        <p><%= huddle.message%></p>
                        <!-- <a class="btn btn-primary" href="#">View Project <span class="glyphicon glyphicon-chevron-right"></span></a> -->
                        <%= link_to 'Join this Huddle', huddle_path(huddle), class: 'btn btn-primary' %>
                    </div>
                </div>
            <% end %>
        <% end %>
        <!-- /.row -->

        <hr>

        <!-- Pagination -->
        <div class="row text-center">
            <div class="col-lg-12">
                <ul class="pagination">
                    <li>
                        <a href="#">&laquo;</a>
                    </li>
                    <li class="active">
                        <a href="#">1</a>
                    </li>
                    <li>
                        <a href="#">2</a>
                    </li>
                    <li>
                        <a href="#">3</a>
                    </li>
                    <li>
                        <a href="#">4</a>
                    </li>
                    <li>
                        <a href="#">5</a>
                    </li>
                    <li>
                        <a href="#">&raquo;</a>
                    </li>
                </ul>
            </div>
        </div>
        <!-- /.row -->

    </div>
    <!-- /.container -->

app/views/huddles/new.html.erb
<div class="container">
	<h1>Create a New Huddle </h1>

	<%= render 'form'%>
</div>

app/views/huddles/show.html.erb
<div class="container">
	<h2>Class: <%= @huddle.subject %></h2>
	<h3>Assignment: <%= @huddle.assignment%> </h3>
	<p>Creator: <%= @huddle.creator%> </p>
	<p>Creator's Email: <%= @huddle.email%> </p>
	<p>Place: <%= @huddle.where%> </p>
	<p>Date:  <%= @huddle.date%> </p>
	<p>Start time: <%= @huddle.start_time %> </p>
	<p>End time: <%= @huddle.end_time %> </p>
	<p>Maximum Number of Participants: <%= @huddle.part_max%></p>
	<p>Message: <%= @huddle.message%></p>

	<h2>Current Participants: </h2>
		<% @participants.each do |participant| %>
			<p> <%= participant.email %></p>
		<% end %>

	<% if @huddle.email != current_user.email %>
		<% if (@huddle.part_max == '' || @participants.size < @huddle.part_max) %>
			<%= form_for @participant do |f| %>
				<%= f.hidden_field :huddle_id, value: @huddle.id %>
				<%= f.submit 'Join this huddle!', :class => 'btn btn-success btn-large'%>
			<% end %>
		<% else %>
			<h2>Sorry this huddle already has the maximum number of participants. 
				Please search for a different huddle</h2>
		<%end%>
	<% end%>

	<h2>Comments: </h2>
		<% @comments.each do |comment| %>
			<h4><%= comment.name %></h4>
			<p><%= comment.message %></p>
		<% end %>

	<h2>Add a comment!</h2>
	<%= render 'comments/form' %>
</div>

app/views/layouts/_alerts.erb
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

app/views/layouts/_nav.erb
<nav class="navbar navbar-default">
  <div class="container fluid">

    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <div  id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <ul class="nav navbar-nav navbar-left">
            <li><a class="navbar-link", href="/">treeHuddle</a></li>

          <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Huddles<b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'Browse', huddles_path %></li>
              <li><%= link_to 'Create New', new_huddle_path %></li>
            </ul>
          </li>
          <% end %>
        </ul>

        <ul class="nav navbar-nav navbar-right">
            <li>
              	<% if user_signed_in? %>
      			  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %>
        		</li>
        		<li>
        			  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
        		</li>
        			<% else %>
        		<li>
        			  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %>
        		</li>
        		<li>
        			  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
        		</li>
  			   <% end %>
        </ul>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TreeHuddleApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
  
  <link href='https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,300,300italic,400italic,700,700italic' rel='stylesheet' type='text/css'>
  <script type="text/javascript" src="jquery-1.11.1.min.js"></script>
   <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
</head>
<body>
<%= render 'layouts/alerts' %>
<%= render 'layouts/nav' %>
<%= yield %>
<footer>
        <hr><div class="container">
            <div class="row">
                <div class="col-lg-10 col-lg-offset-1 text-center">
                    <h4><strong>Contact Us:</strong>
                    </h4>
                    <ul class="list-unstyled">
                        <li><i class="fa fa-envelope-o fa-fw"></i>  <a href="mailto:paul.mr.harrison@gmail.com">paul.mr.harrison@gmail.com</a>
                        </li>
                        <li><i class="fa fa-envelope-o fa-fw"></i>  <a href="mailto:nadin@stanford.edu">nadin@stanford.edu</a>
                        </li>
                    </ul>
                    <hr class="small">
                    <p class="text-muted">Copyright &copy; treeHuddle 2016</p>
                </div>
            </div>
        </div>
    </footer>
</body>
</html>

app/views/participants/_form.html.erb
<% if @participant.errors.present? %>
	<% @participant.errors.full_messages.each do |msg| %>
		<p><%= msg %></p>
	<% end %>
<% end%>

<%= form_for @participant do |f| %>
	<p>
		<%= f.label :email %><br>
		<%= f.email_field :email %>
	</p>
	<%= f.hidden_field :huddle_id, value: @huddle.id %>
	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/welcome/index.html.erb
<header id="top" class="header">
    <div class="container">
        <div class="row">
            <div class="col-md-12" style="height: 20px">
            </div>
        </div>
        <div class ="row">
            <div class="col-md-6">
                <h1 style = "color: white; font-size: 80px;">treeHuddle</h1>
                <h3 style="color: white; font-size: 24px; text-align: left; font-family: 'Montserrat', sans-serif;">Studying in groups should be easy</h3>
            </div>
            <div class="col-sm-4 col-md-3 col-md-offset-5" style="float: right">
                <%= link_to 'Log In', new_user_session_path, class: "btn btn-dark btn-xlarge" %><br>
                <a class="btn btn-dark btn-xlarge" href="#getting-started"> Get Started</a>
            </div>
        </div>
    </div>
</header>




<div id="getting-started" class="services">
    <div class="container">
        <div class="row text-center">
            <div class="col-sm-12 col-md-12">
                    <h1 style="text-align: center"> Find out how treeHuddle can make your life easier!</h1>
                    <iframe align="center" width='600' height='400' src="http://www.youtube.com/embed/0DxmrCyLdF0" frameborder="100"></iframe><br>
                    <div style = "display: inline-block;float: left;margin: 50px;">
                        <h2 style="display:inline; margin: 10px">Ready to start?</h2>
                        <%= link_to 'Sign Up', new_user_registration_path, class: "btn btn-success btn-xlarge" %>
                    </div>
                    <div style = "display: inline-block;float: right;margin: 50px;">
                        <h2 style="display: inline; margin: 10px">Already a member?</h2>
                        <%= link_to 'Log In', new_user_session_path, class: "btn btn-success btn-xlarge" %>
                    </div>
            </div>
        </div>
</div>



<div id="myCarousel" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner" role="listbox">
        <div class="item active">
          <img class="first-slide" src="http://az616578.vo.msecnd.net/files/2016/04/28/635974526628760594-309475862_books.jpg" alt="First slide">
          <div class="container">
            <div class="carousel-caption">
                <div id="words">
              <h1 style="font-size: 72px">Browse & Join</h1>
              <p style="font-size: 42px">existing huddles.</p>
              </div>
            </div>
          </div>
        </div>
        <div class="item">
          <img class="second-slide" src="http://static1.squarespace.com/static/523cc9c9e4b05da1410671ef/t/56df8166859fd0fc993e2943/1457488233169/work--black-background--calendar--write_3325628.jpg?format=1500w" alt="Second slide">
          <div class="container">
            <div class="carousel-caption">
              <strong><h1 style="font-size: 82px; color: white;">Create</h1></strong>
              <p style="font-size: 42px; color: white">new huddles at convenient times for you.</p>
            </div>
          </div>
        </div>
        <div class="item">
          <img class="third-slide" src="http://blog.tigerbookstore.com/wp-content/uploads/2013/04/study.jpg" alt="Third slide">
          <div class="container">
            <div class="carousel-caption">
              <h1 style="font-size: 72px">Meet Up</h1>
              <p style="font-size: 42px">with other students.</p>
            </div>
          </div>
        </div>
      </div>
          <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev" style="padding: 200px">
            <span class="fa fa-arrow-left fa-2x"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next" style="padding: 200px">
            <span class="fa fa-arrow-right fa-2x"></span>
            <span class="sr-only">Next</span>
          </a>
    </div><!-- /.carousel -->